# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: KeJun | BLOG
email: kejun1997@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  二次元智障
baseurl: "/jekyll-theme-materialize" # the subpath of your site, e.g. /blog
url: "https://blog.kejun.tk/" # the base hostname & protocol for your site
# icon
icon-16x16: /images/icon/favicon-16x16.ico
icon-32x32: /images/icon/favicon-32x32.ico
# theme color
theme-color: { 
  default-color: green, 
  home-color: green,
  about-color: red,
  archive-color: pink,
  links-color: purple,
  tags-color: blue
} 
# mobile nav
mobile-hp: /images/tx.jpg
mobile-bg: /images/userbg.png

# Build settings
markdown: kramdown

exclude: [vendor]